[functions.delete-storage-objects]
verify_jwt = true

[functions.og-preview]
verify_jwt = false

[functions.send-campaign-emails]
verify_jwt = true

[functions.fraud-detection]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = true
