/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ParaSaAffiliateRouteImport } from './routes/para-sa-affiliate'
import { Route as ParaSaBuyerRouteImport } from './routes/para-sa-buyer'
import { Route as ParaSaRiderRouteImport } from './routes/para-sa-rider'
import { Route as ParaSaSellerRouteImport } from './routes/para-sa-seller'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaSaAffiliateRoute = ParaSaAffiliateRouteImport.update({
  id: '/para-sa-affiliate',
  path: '/para-sa-affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaSaBuyerRoute = ParaSaBuyerRouteImport.update({
  id: '/para-sa-buyer',
  path: '/para-sa-buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaSaRiderRoute = ParaSaRiderRouteImport.update({
  id: '/para-sa-rider',
  path: '/para-sa-rider',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaSaSellerRoute = ParaSaSellerRouteImport.update({
  id: '/para-sa-seller',
  path: '/para-sa-seller',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/para-sa-affiliate': typeof ParaSaAffiliateRoute
  '/para-sa-buyer': typeof ParaSaBuyerRoute
  '/para-sa-rider': typeof ParaSaRiderRoute
  '/para-sa-seller': typeof ParaSaSellerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/para-sa-affiliate': typeof ParaSaAffiliateRoute
  '/para-sa-buyer': typeof ParaSaBuyerRoute
  '/para-sa-rider': typeof ParaSaRiderRoute
  '/para-sa-seller': typeof ParaSaSellerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/para-sa-affiliate': typeof ParaSaAffiliateRoute
  '/para-sa-buyer': typeof ParaSaBuyerRoute
  '/para-sa-rider': typeof ParaSaRiderRoute
  '/para-sa-seller': typeof ParaSaSellerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/para-sa-affiliate'
    | '/para-sa-buyer'
    | '/para-sa-rider'
    | '/para-sa-seller'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/para-sa-affiliate'
    | '/para-sa-buyer'
    | '/para-sa-rider'
    | '/para-sa-seller'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/para-sa-affiliate'
    | '/para-sa-buyer'
    | '/para-sa-rider'
    | '/para-sa-seller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ParaSaAffiliateRoute: typeof ParaSaAffiliateRoute
  ParaSaBuyerRoute: typeof ParaSaBuyerRoute
  ParaSaRiderRoute: typeof ParaSaRiderRoute
  ParaSaSellerRoute: typeof ParaSaSellerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-sa-affiliate': {
      id: '/para-sa-affiliate'
      path: '/para-sa-affiliate'
      fullPath: '/para-sa-affiliate'
      preLoaderRoute: typeof ParaSaAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-sa-buyer': {
      id: '/para-sa-buyer'
      path: '/para-sa-buyer'
      fullPath: '/para-sa-buyer'
      preLoaderRoute: typeof ParaSaBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-sa-rider': {
      id: '/para-sa-rider'
      path: '/para-sa-rider'
      fullPath: '/para-sa-rider'
      preLoaderRoute: typeof ParaSaRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-sa-seller': {
      id: '/para-sa-seller'
      path: '/para-sa-seller'
      fullPath: '/para-sa-seller'
      preLoaderRoute: typeof ParaSaSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ParaSaAffiliateRoute: ParaSaAffiliateRoute,
  ParaSaBuyerRoute: ParaSaBuyerRoute,
  ParaSaRiderRoute: ParaSaRiderRoute,
  ParaSaSellerRoute: ParaSaSellerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
